<?php

class C_DeleteArticle extends C_Base
{
    protected function Computing()
    {
        parent::Computing(); // TODO: Change the autogenerated stub
        $id_article = $this->toInt($_GET['delete_article'])?: 0;
        if ($id_article) {
            if ($this->mArticles->Delete($id_article)) {
                header("Location: index.php?c=moderate");
                exit;
            } else
                $this->errorMessage = "Ошибка при поптыке удалить запись";
        } else
            $this->errorMessage = "Неправильный идентификатор записи";
    }
}