<?php

class C_ViewArticle extends C_Base
{
    private $article;

    protected function Computing()
    {
        parent::Computing(); // TODO: Change the autogenerated stub
        $idArticle = $this->toInt($_GET['view_article']) ?: 0;
        if ($idArticle) {
            $this->article = $this->mArticles->getById($idArticle);
            $this->title = $this->article['title'];
        } else {
            header("Location: index.php");
            exit;
        }
    }

    protected function Output()
    {
        $variables = array('article' => $this->article);
        $this->content = $this->IncludeView('V_ViewArticle.php', $variables);
        parent::Output();
    }
}
